name: Unit Test Coverage

on: [push]
jobs:
  coverage:
    name: unit test coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v3
        with:
          token: 8b34c879-d5ef-4e40-aa8f-e3990c57b4bc # not required for public repos
          files: coverage.txt