name: Unit Test Coverage

on: [push]
jobs:
  coverage:
    name: unit test coverage
    runs-on: ubuntu-latest
    steps:
      - name: generate coverage results
        run: make cover
      - name: generate text file with results
        run: make coverage_txt
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v3
        with:
          files: coverage.txt